### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by Pilvinen** [fledware/GodotXUnit#4] opened 2020-10-18 14:46 UTC
I have trouble installing this addon.

```
1) Go to AssetLib tab and search for GodotXUnit and Install project. Don't enable yet.
```
Done.

```
2) Include these scripts to your mono project csproj:
- addons/GodotXUnit/GodotTestRunner.cs
- addons/GodotXUnit/Plugin.cs
- addons/GodotXUnit/XUnitDock.cs
```
Done.

```
- execute this command on the cli at the root of your project:
3) nuget restore ./addons/GodotXUnit/GodotXUnitApi/GodotXUnitApi.csproj
```
Done

```
4) Add this reference to your main project:
./addons/GodotXUnit/GodotXUnitApi/GodotXUnitApi.csproj
```
Couldn't do this from Rider's GUI, I had to manually edit my project's .csproj:

```
  <ItemGroup>
    <ProjectReference Include="addons/GodotXUnit/GodotXUnitApi/GodotXUnitApi.csproj" />
  </ItemGroup>
```

Which then results in the error when trying to build:

```
Metadata file 'addons/GodotXUnit/GodotXUnitApi/bin/Debug/GodotXUnitApi.dll' could not be found
```

Help me, fledware, you're my only hope.

**Comment by rexfleischer** [comment] 2020-10-18 20:12
That likely means that the GodotXUnitApi project isn't being built. have you tried just building the GodotXUnitApi project? if that doesnt get you anywhere, can you paste the main .csproj?

also note, this plugin hasn't been tested with godot 3.2.3.

**Comment by Pilvinen** [comment] 2020-10-21 21:34
I'm on .NET Standard 2.1 and Godot 3.2.3.

I've been playing around with GodotXUnit for couple of days now, but there's just no way I can get it running. I guess I'll just lay back for a while and wait until you're ready to update it to .NET Standard.

**Comment by rexfleischer** [comment] 2020-10-21 23:07
I've tested it with the different .Net backends and it works. The issue is with the new godot build for c# in general. I can't get any multi csproj solutions to build with `Godot.NET.Sdk/3.2.3`.

a good work around would be to just entirely remove the `addons/GodotXUnit/GodotXUnitApi/GodotXUnitApi.csproj` file and project reference and just include all of the cs files into the root project. a working example can be found here: https://github.com/fledware/GodotXUnit/tree/hack-example

couple things to note:
* there is only one csproj
* targeting unit test projects will likely not work
* if you do not follow the note in this file, GodotXUnit will not be able to find tests with the GodotFact attribute: addons/GodotXUnit/GodotXUnitApi/GodotFactAttribute.cs

**Comment by rexfleischer** [comment] 2020-10-31 16:26
@Pilvinen did this work out for you?

**Comment by Pilvinen** [comment] 2020-10-31 16:30
No. I spent two days on playing around with it trying out all kinds of things, but eventually just gave up.

I think the instructions could be more detailed and specific. But I'm not sure if that would have helped me because I'm on Godot 3.2.3, .NET Standard 2.1, and C# 8.0.

**Comment by rexfleischer** [comment] 2020-11-05 17:39
it is working with godot 3.2.3 in the branch i showed.

I'm going to close this and do a writeup in the readme on the new godot build issue.

**Closed as completed by rexfleischer** 2020-11-05 17:39 UTC
