### ISSUE TITLE
Merge rider-test-runner branch to master?

### ISSUE THREAD

**Issue by van800** [fledware/GodotXUnit#14] opened 2021-11-11 08:02 UTC
https://github.com/fledware/GodotXUnit/tree/rider-test-runner

**Comment by rexfleischer** [comment] 2021-11-16 17:21
Sorry, there's an issue I'm trying to work through with this, I just haven't been able to get to it again. The issue is that the CI doesn't seem to find tests, and if they do, they don't run and timeout.

here for example: https://github.com/fledware/GodotXUnit/runs/4023521949
* `Execute Tests` here doesn't find any tests
* `Execute Failing Integration Tests` hangs

I'm pretty sure this issue is with how tests are loaded, but I can't seem to find it. Maybe it's related to the error about not finding metadata?

**Comment by van800** [comment] 2021-11-17 11:19
I can reproduce that locally in 10-20 attempts and even attach debugger.
But I can't get, what is wrong.
XUnit AssemblyRunner just doesn't send us any messages after the discovery.
At the same time for example `GodotXUnitRunnerBase._Process` is called just fine.

**Comment by rexfleischer** [comment] 2021-11-17 17:58
Oh, nice. You go the debugger working! 

That's a good bit of info you gave. I'll try to get around to this by next week. I have the entire next week off from work so I should be able to dive into this.

**Comment by rexfleischer** [comment] 2021-11-29 22:19
Got this merged. Thanks and good job!

**Closed as completed by rexfleischer** 2021-11-29 22:19 UTC

**Comment by GeorgeS2019** [comment] 2021-12-04 10:28
> I can reproduce that locally in 10-20 attempts and even attach debugger. But I can't get, what is wrong. XUnit AssemblyRunner just doesn't send us any messages after the discovery. At the same time for example `GodotXUnitRunnerBase._Process` is called just fine.

YES, no more messages.  Need to evaluate if the merge affect (improve or make it less likely)  the chance of getting VS2019 debugging to work.

**Comment by GeorgeS2019** [comment] 2021-12-04 10:35
@rexfleischer  I have evaluated a few Godot c# test framework.  You can do VS2019 debugging through them. 

I recommend not to merge Rider on the main branch. 
It is obviously that the merge bring more Rider friendly BUT without **sufficient testing how friendly** with the competitive IDE like VS2019.

There are many Godot C# test framework out there. Only GodotXunit has Rider support for obvious reason.

The alternative will be to bring GodotXUnit to something **GodotNUnit** which is compatible for VS2019. I hope that is OK for you, using most of the excellent codes provided by the original GodotXunit.

**Comment by rexfleischer** [comment] 2021-12-07 17:33
XUnit is definitely compatible for VS2019. And the rider compatibility doesn't change the underline process. The rider changes generally only changes how the tests are gathered and bootstrapped within the rider IDE.

**Comment by GeorgeS2019** [comment] 2021-12-07 17:38
@rexfleischer 
I just replied to your previous remark. 

> The rider changes generally only changes how the tests are gathered and bootstrapped within the rider IDE.

Can the VS2019 take advantage of that?
